### ISSUE TITLE
meaningless entryTypeDefinition.aCollectionOf property defiition

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/beacon-v2#114]
Hi all,

There is invalid [entryTypeDefinition.aCollectionOf](https://github.com/ga4gh-beacon/beacon-v2/blob/7c64fdf3b18c36cfa7279d610982224e1bf48c4d/framework/json/configuration/entryTypeDefinition.json#L10) property definition in the spec.

```json
"aCollectionOf": {
    "description": "If the entry type is a collection of other entry types, (e.g. a Dataset is a collection of Records), then this attribute must list the entry types that could be included. One collection type could be defined as included more than one entry type (e.g. a Dataset could include Individuals or Genomic Variants), in such cases the entries are alternative, meaning that a given instance of this entry type could be of only one of the types (e.g. a given Dataset contains Individuals, while another Dataset could contain Genomic Variants, but not both at once).",
    "includedConcepts": {
        "$ref": "../common/basicElement.json",
        "type": "array"
    }
},
```
`"includedConcepts"` here is something to be ignored by schemas, so basically equivalent
```
"aCollectionOf": {}
```

Best,

Dmitry

**Comment by datsirul** [comment]
@jrambla This issue by @redmitry was also found by our work on the code generator. The file [`/entryTypeDefinition.yaml`](https://github.com/ga4gh-beacon/beacon-v2/blob/7c64fdf3b18c36cfa7279d610982224e1bf48c4d/framework/src/configuration/entryTypeDefinition.yaml) curently has:

```yaml
  aCollectionOf:
    description: If the entry type...
    includedConcepts:
      type: array
      $ref: ../common/basicElement.yaml
```

I'm not sure what is the reason for the `includedConcepts` key, but for it to be a valid OpenAPI object it should be removed, like so:

```yaml
  aCollectionOf:
    description: If the entry type...
    type: array
    $ref: ../common/basicElement.yaml
```

**Note:**
After fixing the `.yaml` files, the `.json` should be fixed as well by running the schema conversion script located in the [bin folder](https://github.com/ga4gh-beacon/beacon-v2/tree/main/bin)
