### ISSUE TITLE
Invalid CollectionsResponse in the OpenAPI 

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/beacon-v2#116]
Hi all,

[cohorts/endpoints.json](https://github.com/ga4gh-beacon/beacon-v2/blob/main/models/json/beacon-v2-default-model/cohorts/endpoints.json) and [datasets/endpoints.json](https://github.com/ga4gh-beacon/beacon-v2/blob/main/models/json/beacon-v2-default-model/datasets/endpoints.json) have CollectionsResponse response object derfined as a 
choice of beaconBooleanResponse, beaconCountResponse and beaconCollectionsResponse which is wrong.

Should be defined as [beaconCollectionsResponse](https://github.com/ga4gh-beacon/beacon-v2/blob/main/framework/json/responses/beaconCollectionsResponse.json) precising the type according the endpoint [cohorts/defaultSchema.json](https://github.com/ga4gh-beacon/beacon-v2/blob/main/models/json/beacon-v2-default-model/cohorts/defaultSchema.json) or [cohorts/defaultSchema.json](https://github.com/ga4gh-beacon/beacon-v2/blob/main/models/json/beacon-v2-default-model/cohorts/defaultSchema.json).

Best,

Dmitry

**Comment by mbaudis** [comment]
True. And the "ResultsOKResponse" should also only have this value, right?

```
components:
  responses:
    ResultsOKResponse:
      description: Successful operation.
      content:
        application/json:
          schema:
            $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconCollectionsResponse.json
    CollectionsResponse:
      description: Successful collection list operation.
      content:
        application/json:
          schema:
            $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconCollectionsResponse.json
```

**Comment by redmitry** [comment]
> True. And the "ResultsOKResponse" should also only have this value, right?

This would be an improvement because neither "CollectionsResponse" nor "ResultsOKResponse" defins the entryType.
The question how to do this in json schema with no pain (not rewriting ALL components)
I should think a little bit...

**Comment by jrambla** [comment]
Let me disagree, a query to a collection could return a boolean or count response, telling he number of collections (datasets or cohorts in the Bv2 Model) that fulfill the query. 
The question could be: "how many cohorts do you have with men above 50 yo?"

**Comment by mbaudis** [comment]
@Jordi That is all fine and I agree that this could be a use case; and also that there is IMO a need for having a general response granularity and overall the boolean/count response options.

The response still we have to be fixed from `beaconResultsetsResponse` to `beaconCollectionsResponse` etc.

But then in the long run IMO response granularity should be per resultSet to allow especially different granularities in aggregators, but also for Beacons w/ multiple datasets. (AND collections responses could also be resultSets since we're having this construct - e.g. datasets have cohorts. Same for filteringTerms which are per dataset etc - we have to deal with this already!). Just not sure if this would make things more simple (only one response type with different granularities) or more complex ...

**Comment by mbaudis** [comment]
... so in the short run `beaconResultsetsResponse` => `beaconCollectionsResponse` should do the trick, right?

**Comment by redmitry** [comment]
> a query to a collection could return a boolean or count response,

... I see no way for boolean response for "collections" in the beaconCollectionsResponse. The items in the "collections" are entryType(s) [beaconCollectionsResponse.json](https://github.com/ga4gh-beacon/beacon-v2/blob/7c64fdf3b18c36cfa7279d610982224e1bf48c4d/framework/json/responses/beaconCollectionsResponse.json#L24)

I also wonder, how could I know if the response is the beaconCollectionsResponse or beaconResultsetsResponse from the configuration/map ?

**Comment by mbaudis** [comment]
@redmitry @jrambla 

> ... I see no way for boolean response for "collections" in the beaconCollectionsResponse. The items in the "collections" are entryType(s) [beaconCollectionsResponse.json](https://github.com/ga4gh-beacon/beacon-v2/blob/7c64fdf3b18c36cfa7279d610982224e1bf48c4d/framework/json/responses/beaconCollectionsResponse.json#L24)

That is true but if you drop the requirement on `response` like that:

```
required:
  - meta
  - responseSummary
```

... you can use boolean or count granularity.

> I also wonder, how could I know if the response is the beaconCollectionsResponse or beaconResultsetsResponse from the configuration/map ?

Yes, not possible righty now; only defined in the OpenAPI endpoints.

We actually save such info min our configs:

```
individual:
  request_entity_path_id: individuals
  response_entity_id: individual
  collection: individuals
  response_schema: beaconResultsetsResponse
  beacon_schema:
    entity_type: individual
    schema: https://progenetix.org/services/schemas/individual/

cohort:
  request_entity_path_id: cohorts
  response_entity_id: cohort
  collection: collations
  response_schema: beaconCollectionsResponse
  beacon_schema:
    entity_type: cohort
    schema: https://progenetix.org/services/schemas/cohort/
  pagination:
    skip: 0
    limit: 10
```
