### ISSUE TITLE
Inconsistencies in `beaconMap` between entry types and paths (run, analysis)

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-v2#125]
The `beaconMap` schema has a number of inconsistencies in the `endpoints` definitions which preclude its use for determining path <-> entry type relations. Starting here: 

https://github.com/ga4gh-beacon/beacon-v2/blob/afaf76ac3e4ce6c48fa5da571b7883046ccef020/models/src/beacon-v2-default-model/beaconMap.yaml#L19

```
      runs:
        returnedEntryType: run
        url: https://exampleBeacons.org/datasets/{id}/runs
      analyses:
        returnedEntryType: analysis
        url: https://exampleBeacons.org/datasets/{id}/analyses
```
... use the wrong entry type key; should be:

```
      run:
        returnedEntryType: run
        url: https://exampleBeacons.org/datasets/{id}/runs
      analysis:
        returnedEntryType: analysis
        url: https://exampleBeacons.org/datasets/{id}/analyses
```

This is repeated throughout the document, but not everywhere; e.g. while it is `runs` in `individual`, it is `run` in biosample.

**Comment by redmitry** [comment]
I see no inconsistency here.

The endpoint name shouldn't reflect neither entry type name, nor the path.
In the analogue to the OpenAPI we have "operationId" which is the  semantic name for the operation:
https://spec.openapis.org/oas/v3.1.0#operation-object
It usually reflects the operation purpose like "getBiosampleById".

Cheers,

D.

**Comment by mbaudis** [comment]
@redmitry Well, I wouldn't mind how you name your endpoint as long as path & entry type are provided. But it is inconsistent:

```
  individual:
...
    endpoints:
...
      runs:
        returnedEntryType: run
        url: https://exampleBeacons.org/individuals/{id}/runs
      analyses:
        returnedEntryType: analysis
        url: https://exampleBeacons.org/individuals/{id}/analyses
```

compared to:

```
  biosample:
...
    endpoints:
      run:
        returnedEntryType: run
        url: https://exampleBeacons.org/biosamples/{id}/runs
      analysis:
        returnedEntryType: analysis
        url: https://exampleBeacons.org/biosamples/{id}/analyses
```

Therefore fix needed. Also: Such inconsistencies can lead to a break of implementations, e.g. if you collect all possible endpoints etc.
