### ISSUE TITLE
Invalid Syntax in `beaconErrorResponse.yaml`

### ISSUE THREAD

**Issue by datsirul** [ga4gh-beacon/beacon-v2#135]
The file [`beaconErrorResponse.yaml`](https://github.com/ga4gh-beacon/beacon-v2/blob/4db7f83ca546547c9901fed719400bdbb6154020/framework/src/responses/beaconErrorResponse.yaml) contains invalid OpenAPI syntax.

**Existing Syntax:**

```yaml
$schema: https://json-schema.org/draft/2020-12/schema
type: object
description: >-
  An unsuccessful operation.
properties:
  meta:
    $ref: ./sections/beaconResponseMeta.yaml
  error:
    $ref: ../common/beaconCommonComponents.yaml#/definitions/BeaconError
required:
  - meta
  - error
additionalProperties: true
```

**Corrected Syntax:**
As this file is a response definition, it should be defined as a `response` object in the OpenAPI specification. The correct syntax should be:

```yaml
$schema: https://json-schema.org/draft/2020-12/schema
type: object
description: >-
  An unsuccessful operation.
content:
  application/json:
    schema:
      type: object
      properties:
        meta:
          $ref: ./sections/beaconResponseMeta.yaml
        error:
          $ref: ../common/beaconCommonComponents.yaml#/definitions/BeaconError
      required:
        - meta
        - error
      additionalProperties: true
```

**Reference:**
[OpenAPI Specification - Describing Responses](https://swagger.io/docs/specification/describing-responses/)

**Note:**
After fixing the `.yaml` files, the `.json` should be fixed as well by running the schema conversion script located in the [bin folder](https://github.com/ga4gh-beacon/beacon-v2/tree/main/bin).

**Comment by jrambla** [comment]
Hi Daniel,

Here is where discussion starts to get interesting...
The changes you are suggesting would make OpenAPI to properly integrate the  referenced schema, right?
But, how much will it interfere with using that schema outside of OpenAPI? (Which we do, a lot)

**Comment by datsirul** [comment]
Hi Jordi,

It seems that all endpoints have a `default` response of:

```yaml
default:
  description: An unsuccessful operation
  $ref: ./responses/beaconErrorResponse.yaml
```

Which leads to the `beaconErrorResponse.yaml` file, but, the syntax I posted is the correct way of defining a response (as described in the OpanAPI docs). For example, without this fix, this error response object is not properly generated when using a code generator with the `.yaml` files.

I'm not sure in what ways this schema is used outside of OpenAPI, as you mentioned. Are there other tools/frameworks that use these files or are you referring to manually creating a Beacon implementation from the schema? Would be great to get some context so I could better address the concern.
