### ISSUE TITLE
Invalid Syntax in `includeResultsetResponses`

### ISSUE THREAD

**Issue by datsirul** [ga4gh-beacon/beacon-v2#136]
The endpoints that use the `includeResultsetResponses` parameter contain invalid OpenAPI syntax.

These include the following files:

- [`analyses/endpoints.yaml`](https://github.com/ga4gh-beacon/beacon-v2/blob/4db7f83ca546547c9901fed719400bdbb6154020/models/src/beacon-v2-default-model/analyses/endpoints.yaml)
- [`biosamples/endpoints.yaml`](https://github.com/ga4gh-beacon/beacon-v2/blob/4db7f83ca546547c9901fed719400bdbb6154020/models/src/beacon-v2-default-model/biosamples/endpoints.yaml)
- [`genomicVariations/endpoints.yaml`](https://github.com/ga4gh-beacon/beacon-v2/blob/4db7f83ca546547c9901fed719400bdbb6154020/models/src/beacon-v2-default-model/genomicVariations/endpoints.yaml)
- [`individuals/endpoints.yaml`](https://github.com/ga4gh-beacon/beacon-v2/blob/4db7f83ca546547c9901fed719400bdbb6154020/models/src/beacon-v2-default-model/individuals/endpoints.yaml)
- [`runs/endpoints.yaml`](https://github.com/ga4gh-beacon/beacon-v2/blob/4db7f83ca546547c9901fed719400bdbb6154020/models/src/beacon-v2-default-model/runs/endpoints.yaml)

Existing Syntax:

```yaml
includeResultsetResponses:
  $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/common/beaconCommonComponents.json#/definitions/IncludeResultsetResponses
```

**Corrected Syntax:**
As this object is a parameter definition, it should be defined as a `parameter` object in the OpenAPI specification. The correct syntax should be:

```yaml
includeResultsetResponses:
  name: includeResultsetResponses
  in: query
  schema:
    $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/common/beaconCommonComponents.json#/definitions/IncludeResultsetResponses
```

**Reference:**
[OpenAPI Specification - Describing Parameters](https://swagger.io/docs/specification/describing-parameters/)

**Note:**
After fixing the `.yaml` files, the `.json` should be fixed as well by running the schema conversion script located in the [bin folder](https://github.com/ga4gh-beacon/beacon-v2/tree/main/bin).
