### ISSUE TITLE
Invalid Syntax in `securityLevels` 

### ISSUE THREAD

**Issue by datsirul** [ga4gh-beacon/beacon-v2#137]
The file [`beaconConfigurationSchema.yaml`](https://github.com/ga4gh-beacon/beacon-v2/blob/4db7f83ca546547c9901fed719400bdbb6154020/framework/src/configuration/beaconConfigurationSchema.yaml) contains invalid OpenAPI syntax in it's default value.

**Existing Syntax:**

```yaml
securityLevels:
    description: All access levels supported by the Beacon. Any combination is
      valid, as every option would apply to different parts of the Beacon.
    type: array
    items:
      enum:
        - PUBLIC
        - REGISTERED
        - CONTROLLED
      default:
        - CONTROLLED
```

**Corrected Syntax:**
The default value should be defined at the same level as the other properties under `securityLevels`:

```yaml
securityLevels:
  description: All access levels supported by the Beacon. Any combination is
    valid, as every option would apply to different parts of the Beacon.
  type: array
  items:
    type: string
    enum:
      - PUBLIC
      - REGISTERED
      - CONTROLLED
  default:
    - CONTROLLED
```

**Reference:**
[OpenAPI Specification - Describing Parameters - Default Parameter Values](https://swagger.io/docs/specification/describing-parameters/)

**Note:**
After fixing the `.yaml` files, the `.json` should be fixed as well by running the schema conversion script located in the [bin folder](https://github.com/ga4gh-beacon/beacon-v2/tree/main/bin).

**Comment by jrambla** [comment]
Seems fine to me.  PR, please

**Comment by mbaudis** [comment]
+1

**Comment by mbaudis** [comment]
Again too fast with the +1. It is a mix of both changes:

* the `default` parameter is at the root level of the object as @datsirul pointed out (it is not a default for the items...)
* as @redmitry points out the default should be an array of one or more of the ENUM values
* it is correct in the JSON version which emphasizes the correct way to do the code editing as @datsirul always adds to his issues (+1):

> Note: After fixing the .yaml files, the .json should be fixed as well by running the schema conversion script located in the [bin folder](https://github.com/ga4gh-beacon/beacon-v2/tree/main/bin).

```
    type: array
    default:
      - - CONTROLLED
    items:
      enum:
        - PUBLIC
        - REGISTERED
        - CONTROLLED
```
