### ISSUE TITLE
`filteringTerms`: Add `excluded` flag

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-v2#63]
There is currently no way to exclude specific ontologyTerms in filter queries although this would be desirable to expand query options (especially regarding the limitation of not having Booleans) and to stay in line with Phenopackets (which has an [`excluded` flag e.g. in `PhenotypicFeature`](https://phenopacket-schema.readthedocs.io/en/latest/phenotype.html?highlight=excluded#excluded).

(There is a current workaround to use some custom filter design, e.g. pre-pending an ontologyTerm in a request with `!` - but this is non-standard & only would work for individual Beacons.)

Proposal:

```
  OntologyFilter:
    type: object
    description: Filter results to include records that contain a specific ontology
      term.
    required:
      - id
    properties:
      id:
        type: string
        description: >-
          Term ID to be queried, using CURIE syntax where possible.
        example: HP:0002664
      includeDescendantTerms:
        type: boolean
        default: true
        description: >-
          Define if the Beacon should implement the ontology hierarchy,
          thus query the descendant terms of `id`.
      similarity:
        type: string
        enum:
          - exact
          - high
          - medium
          - low
        default: exact
        description: >-
          Allow the Beacon to return results which do not match the filter
          exactly, but do match to a certain degree of similarity. The Beacon defines
          the semantic similarity model implemented and how to apply the thresholds
          of 'high', 'medium' and 'low' similarity.
      scope:
        type: string
        description: The entry type to which the filter applies
        example: biosamples
      excluded:
        description: >-
          Flag to indicate whether the filtering term was observed or not. The default is `false`,
          _i.e._ will be selected for **existence** of the term.
        type: boolean
        default: false
```
